version: "3.7"
services:
  composer:
    image: composer:1.10.26
    volumes:
      - ./:/app
    command: install --ignore-platform-reqs
  php:
    image: php:7.4-fpm
    volumes:
      - ./:/var/www/html
  nginx:
    image: nginx:1.20
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    links:
      - php
  phpunit:
    image: php:7.4-cli
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
