preset: page
fields:
  link:
    type: legacyLink
    linkTypes:
      - page
      - file
    pages:
      limit: 1
      image:
        cover: true
    files:
      search: false
      image:
        cover: true
  requiredLink:
    type: legacyLink
    required: true
  structure:
    fields:
      legacyLink: true
  blocks:
    pretty: true
    fieldsets:
      test:
        name: Test
        icon: bolt
        fields:
          legacyLink: true
