preset: page
fields:
  link:
    type: link
    linkTypes:
      - page
      - file
    pages:
      limit: 1
      image:
        cover: true
    files:
      search: false
      image:
        cover: true
  structure:
    fields:
      link: true
